version: "3"

services:
  errbit:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - RACK_ENV=development
      - MONGO_URL=mongodb://mongo:27017/errbit
    volumes:
      - .:/app
  mongo:
    image: mongo:4.1
    ports:
      - "27017"
